version: "3.7"
services:

  server:
    container_name: upspeak_server
    environment:
      - POSTGRES_URL=postgres://postgres:password@db:5432/upspeak_dev?sslmode=disable
      - PORT=8080
      - ENV=development
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
      - migrate
    networks:
      - fullstack


  db:
    image: postgres:latest
    container_name: upspeak_db_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=upspeak_dev
      - DATABASE_HOST=db
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - fullstack

  migrate:
    image: migrate/migrate
    networks:
      - fullstack
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:password@db:5432/upspeak_dev?sslmode=disable", "up"]
    depends_on:
      - db

  migrate-down:
    image: migrate/migrate
    networks:
      - fullstack
    volumes:
      - ./migrations:/migrations
    # command: ["-path", "/migrations", "-database",  "postgres://postgres:password@db:5432/upspeak_dev?sslmode=disable", "down"]
    depends_on:
      - db

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161
    networks:
      - local_nsq
      - fullstack

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151
    networks:
      - local_nsq

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqd
    ports:
      - 4171:4171
    networks:
      - local_nsq


volumes:
  db:

# Networks to be created to facilitate communication between containers
networks:
  local_nsq:
    driver: bridge
  fullstack:
    driver: bridge
