/**
 * Create users table. All exposed API calls happen in some users' scope.
 */
create table public.users (
    id bigint default generate_id() not null primary key, -- autogenerated
    username character varying(256) not null unique,
    email_primary text not null unique, -- Main communication email
    display_name text, -- User's publicly displayed name
    password text not null, -- Please store a hash here
    created_at timestamp with time zone not null, -- Time since when user is a member
    is_verified boolean default false not null, -- Whether user account was verified
    is_active boolean default false not null -- Whether user account is active
);
