/**
 * Create users table. All exposed API calls happen in some users' scope.
 */
create table users (
    id bigint default generate_id() not null, -- autogenerated
    username character varying(256) not null,
    password text not null, -- Please store a hash here
    email_primary text not null, -- Main communication email
    created_at timestamp with time zone not null, -- Time since when user is a member
    is_verified boolean default false not null, -- Whether user account was verified
    is_active boolean default false not null, -- Whether user account is active
    display_name text -- User's publicly displayed name
);
